export {
  type BroadcastRoute,
  type ConversationRoute,
  type CrmHistoryState,
  type CrmRoute,
  type CustomerRoute,
  normalizePath,
  type OpportunityRoute,
  owningWorkspace,
  parseRoute,
  pathForRoute,
  type RouteOrigin,
  readHistoryOrigin,
  type Workspace,
  type WorkspaceRoute,
} from './route-model'
